Hello Microverse
shelly8/Hello-Microverse pull request #3
Opened 2022-03-16 15:36 UTC by shelly8

In this project the following has been done: 
- Added a html file
- Added an index.css
- Added a test.md file
- Added npm packages

2022-03-16 16:11 UTC, aimemalaika requested changes
Hi @shelly8, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## Highlights
- Nice HTML structure ✅ 
- meaningful commit message ✅ 

## Required Changes ♻️

- [ ] Consider adding a descriptive summary of changes made to your pull request
- [ ] Kindly add a descriptive description on your pull request, like what all you have worked with to this branch.
- [ ] Kindly make sure that all linters passed
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 16:11 UTC, aimemalaika commented on README.md
> +
- [ ] consider adding more description to your readme. like social media links, project screenshots. Consider using the [Microverse readme template](https://github.com/microverseinc/readme-template).

2022-03-17 13:45 UTC, BenMukebo approved these changes
# STATUS: Approved  🎉 

## Hi *** @shelly8 , *** 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media1.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 15:02 UTC, shelly8 commented
Good day to you  Aime malaika  . I thank you for reviewing my code and
showing me where I need to make the necessary changes.

On Wed, 16 Mar 2022 at 19:14, Aime Malaika ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @shelly8 <https://github.com/shelly8>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: the-simpsons-homer-simpson]
> <https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif>
> Highlights
>
>    - Nice HTML structure ✅
>    - meaningful commit message ✅
>
> Required Changes ♻️
>
>    - Consider adding a descriptive summary of changes made to your pull
>    request
>    - Kindly add a descriptive description on your pull request, like what
>    all you have worked with to this branch.
>    - Kindly make sure that all linters passed
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/shelly8/Hello-Microverse/pull/3#discussion_r828178794>
> :
>
> > +# Hello-Microverse
>
> +
>
> +# Project Name
>
> +
>
> +Hello Microverse project
>
> +
>
> +
>
> +## Built With
>
> +
>
> +- HTML
>
> +- CSS
>
> +
>
> +
>
> +## Show your support
>
> +
>
> +Give a ⭐️ if you like this project!
>
> +
>
>
>
>    - consider adding more description to your readme. like social media
>    links, project screenshots. Consider using the Microverse readme
>    template <https://github.com/microverseinc/readme-template>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shelly8/Hello-Microverse/pull/3#pullrequestreview-911883097>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ6ZZRBDVKICFF6YHXOF6BLVAICH5ANCNFSM5Q4IHKTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-17 15:04 UTC, shelly8 commented
Good day to you Ben Mukebo. Thank you for reviewing my code.

On Thu, 17 Mar 2022 at 16:45, Kasongo Mukebo Ben ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> STATUS: Approved 🎉 Hi *** @shelly8 <https://github.com/shelly8> , *** 👋
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it
> Congratulations! 🎉 🎉 🎉
>
>
> <https://camo.githubusercontent.com/7cd14f6f1e3a67521a1c29720881df4b94f333bf7455cdfefba76144e3484566/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f323675346c4f4d41384a4b536e4c39556b2f67697068792e676966>
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me on( @BenMukebo <https://github.com/BenMukebo>
> ) in your question so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shelly8/Hello-Microverse/pull/3#pullrequestreview-913165430>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ6ZZRFYEG3V6ZA5VSHLZQ3VAMZO5ANCNFSM5Q4IHKTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-23 17:42 UTC, merged